### ISSUE TITLE
Fn+F1 Decreases Subtitle Size

### ISSUE THREAD

**Issue by punctdan** [ZeroUnderscoreOu/Random#1]
I use "YouTube_Subtitles_Shortcut_Override.user.js" but I have a problem probably specific to my laptop model (Asus VivoBook). When I want to mute/unmute the volume using Fn+F1 shortcut, YouTube decreases the subtitle size. It's pretty annoying. It would be nice if this shortcut was disabled.

**Comment by ZeroUnderscoreOu** [comment]
That's weird.
Open the browser console and post the following code there. Then click somewhere on the page to bring focus back to it. Then press the combination you use for muting. You should see several lines printed in the console (probably two, first when you press `Fn` and second when you press `F1`). Paste the result here.

```JS
function KB_Test(EvData) {
	console.log(EvData.code, EvData.key, EvData.keyCode, EvData.which, EvData.charCode,
		EvData.ctrlKey, EvData.altKey, EvData.shiftKey, EvData.metaKey);
};

document.addEventListener("keydown", KB_Test, true);
```

**Comment by punctdan** [comment]
This is what I get when I'm pressing Fn+F1:

`AudioVolumeMute AudioVolumeMute 173 173 0 false false false false`

It looks like it counts it as one key press. I have an Fn lock and tried it on and off, it still shows the line above.

**Comment by ZeroUnderscoreOu** [comment]
As far as I can tell this is indeed an issue specific to your notebook, and not relevant to the script itself. YouTube confuses your media keys with normal keys. I added a check that should block mute/volume up/volume down key press events from firing. This should solve your problem.

https://github.com/ZeroUnderscoreOu/Random/commit/7912eb7ccd2f98a9c16cb6e4c4e60226109735a4

**Comment by punctdan** [comment]
I tested it, it works. Thank you very much!
